# 공통 설정
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    serverTimezone: UTC
    
---

# 로컬 환경 설정

spring:
  config:
    activate:
      on-profile: default
#  profiles: default
  datasource:
    master:
#      jdbc-url: jdbc:log4jdbc:mysql://kms-master.mysql.database.azure.com:3306/mtc
      jdbc-url: jdbc:log4jdbc:sqlserver://usimsa-kms-db.database.windows.net;database=usimsa-kms-sqldb
      username: master
      password: megazone!234
#    slave:
#      jdbc-url: jdbc:log4jdbc:mysql:loadbalance://kms-slave1.mysql.database.azure.com:3306,kms-slave2.mysql.database.azure.com:3306/mtc
#      username: master
#      password: megazone!234
        
      read-only: true # Slave DB는 Read만
      # 로드 밸런싱을 위한 속성 설정
      properties:
        # 로드 밸런싱을 위한 연결 그룹 설정
        loadBalanceConnectionGroup: first
        # JMX를 통한 로드 밸런싱 연결 관리를 활성화
        ha.enableJMX: true

  mvc:
    view:
      prefix: /WEB-INF/views/   # Controller가 리턴시 앞에붙는 경로 명
      suffix: .jsp              # Controller가 리턴시 뒤에붙는 경로 명
  
  # 화면 자동반영 관련 설정
  devtools:
    livereload:
      enabled: true
      
# Mybatis 설정
mybatis:
  # default Package location - resultType의 Alias를 지정합니다.
  type-aliases-package: com.megazone.www.VO
  # mapper location - 바라 볼 xml 파일을 지정합니다.
  mapper-locations: classpath:mapper/*.xml
  # column name to camel case - 반환 받는 컬럼명을 CamelCase로 받는 설정을 합니다.
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8